### ISSUE TITLE
Please add a license to the repository to enable reuse of code

### ISSUE THREAD

**Issue by rdraijer** [technologyreview/technologyreview.github.io#1]
Thank you for making the excellent article ['Can you make AI fairer than a judge? Play our courtroom algorithm game'](https://www.technologyreview.com/2019/10/17/75285/ai-fairer-than-judge-criminal-risk-assessment-algorithm/). 

I would like to reuse part of the code for a bias/fairness-training to be used within the Dutch Central Government. By open sourcing the code used in the article it is implied that reuse is allowed. However by licensing the repository we can know for sure what we can do with it. 

See also: [Github: Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by mollfrey** [comment]
Hi @rdraijer!
Thanks for reaching out about this.  It's being looked into.  Hopefully we'll have an answer about the license in a timeframe that works for your purposes!

**Comment by rdraijer** [comment]
Thank you for the quick response. I'm positive the timeframe will work for our purpose.

**Comment by mollfrey** [comment]
@rdraijer -- I wanted to let you know that we've just added the [Creative Commons Attribution ShareAlike 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license to the project.  I hope that will help with your use case.

Thanks for your patience!

**Comment by rdraijer** [comment]
Thank you for providing the License. Nice choice as well!

**Comment by mollfrey** [comment]
Glad to help!  Hope the training works out well!
